### ISSUE TITLE
Custom entry lookup searches across multiple contexts

### ISSUE THREAD

**Issue by ttasovac** [BCDH/TEI-Completer#18]
If the configuration file has multiple autocomplete contexts, like this:

```xml
     <autoComplete>
        <context>//w</context>
        <attribute>@lemma</attribute>
        <selection>./text()</selection>
        <request>
            <url>$baseUrl/forms/$selection</url>
        </request>
        <response>
            <transformation>getLemmaOutput.js</transformation>
        </response>
    </autoComplete>
    <autoComplete>
        <context>//rs[@type='place']</context>
        <attribute>@corresp</attribute>  
        <selection>./text()</selection>
        <request>
            <url>$baseUrl/entities/places/$selection</url>
        </request>
        <response>
            <transformation>getPlaceOutput.js</transformation>
        </response>
    </autoComplete>
```

the custom lookup will not always respect the context from which it was called.

Let's say the user calls up a custom look from `<w>` and tries to autocomplete on `@lemma`. Then:

- if the user simply types in the look up window, relying on autocomplete, the lookup will actually use both (or probably all, if there are more than two) URLs from the configuration table:
  ![](https://i.imgur.com/tHtwlAb.png)
  In the above screenshot, the first two results are from `$baseUrl/forms/$selection` and the second two results are from `$baseUrl/entities/places/$customLookup`
- when the user clicks on the search button, the right call is made (`$baseUrl/forms/$customLookup`), but see also #17 

Please make sure that the custom lookups only use the one lookup url for the given context.

**Comment by marmoure** [comment]
@ttasovac 
I made a potential fix, Can you please provide me with `getPlaceOutput.js` file and the keywords you used for search as well as the Xml.
I will test and submit a PR shortly.
