### ISSUE TITLE
request url can't handle whitespaces

### ISSUE THREAD

**Issue by linxOD** [BCDH/TEI-Completer#3]
Hello. I have an issue with the request url when there is a whitespace in the selection input. I hope someone can help!

My config:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://humanistika.org/ns/tei-completer">
    <server>
        <baseUrl>https://my-endpoint-url</baseUrl>
    </server>
    <autoComplete>
        <context>//rs</context>
        <attribute>@ref</attribute>
        <dependent default="person">@type</dependent>
        <selection>@n</selection>
        <request>
            <url>$baseUrl/$dependent/?q=$selection</url>
        </request>
    </autoComplete>
</config>
```
Example repsonse url (does not work):
```
https://my-endpoint-url/dependent/?q=input string
```

if the "input string" contains a whitespace I receive this error: 
```
14:24:57.894 [AWT-EventQueue-0] ERROR org.humanistika.oxygen.tei.completer.remote.impl.JerseyClient - Illegal character in query at index 76: https://my-endpoint-url/dependent/?q=input string
java.net.URISyntaxException: Illegal character in query at index 76: https://my-endpoint-url/dependent/?q=input string
```

Example response url (works):
https://my-endpoint-url/dependent/?q=input%20string
If I manually add the unicode for whitespaces it works.

Is there a way to pre-transform the input in the config?
Or can you fix this in your client?

**Comment by adamretter** [comment]
@linxOD I made a small fix and just published version 1.2.0. I hope that helps you.

**Comment by linxOD** [comment]
@adamretter tested and works like a charm. thank you!

**Comment by adamretter** [comment]
@linxOD You are very welcome :-)
