### ISSUE TITLE
Debugging Content Completion Assistant in custom framework

### ISSUE THREAD

**Issue by linxOD** [BCDH/TEI-Completer#4]
Hello,
with the newest version 25 of Oxygen the TEI-Completer blocks the attribute autocompleter assistant of custom frameworks. 
Here is more information about it in the Oxygen Forum:
https://www.oxygenxml.com/forum/common-problems/topic25094.html

Could you please investigate and provide a potential fix?

Thank you!

**Comment by adamretter** [comment]
@linxOD I am afraid that there is no longer any funding for me to work on this project, so it is unlikely that I will undertake lengthly pieces of work on it at this time. If you wanted to contribute a fix, I could perhaps attempt to review and merge it...

**Comment by ttasovac** [comment]
I'm closing this —  we're working on the new version that will work with newer releases of oXygen.
